//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nameless.Ledger {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Headers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Headers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nameless.Ledger.Headers", typeof(Headers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amex.
        /// </summary>
        internal static string AMEX {
            get {
                return ResourceManager.GetString("AMEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brokers.
        /// </summary>
        internal static string BROKERAGE_FIRMS {
            get {
                return ResourceManager.GetString("BROKERAGE_FIRMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco central.
        /// </summary>
        internal static string CENTRAL_BANKS {
            get {
                return ResourceManager.GetString("CENTRAL_BANKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco comercial.
        /// </summary>
        internal static string COMMERCIAL_BANKS {
            get {
                return ResourceManager.GetString("COMMERCIAL_BANKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooperativas de credito.
        /// </summary>
        internal static string CREDIT_UNIONS {
            get {
                return ResourceManager.GetString("CREDIT_UNIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inversiones.
        /// </summary>
        internal static string INVESTMENT_BANKS {
            get {
                return ResourceManager.GetString("INVESTMENT_BANKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prestamos.
        /// </summary>
        internal static string LOANS {
            get {
                return ResourceManager.GetString("LOANS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master card.
        /// </summary>
        internal static string MASTER_CARD {
            get {
                return ResourceManager.GetString("MASTER_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No especificado.
        /// </summary>
        internal static string NOT_ESPECIFIED {
            get {
                return ResourceManager.GetString("NOT_ESPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco de tienda departamental.
        /// </summary>
        internal static string RETAIL_BANKS {
            get {
                return ResourceManager.GetString("RETAIL_BANKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahorros.
        /// </summary>
        internal static string SAVINGS {
            get {
                return ResourceManager.GetString("SAVINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa.
        /// </summary>
        internal static string VISA {
            get {
                return ResourceManager.GetString("VISA", resourceCulture);
            }
        }
    }
}
