-- MySQL Script generated by MySQL Workbench
-- Tue Oct  3 11:04:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_ledger
-- -----------------------------------------------------
-- Ledger Money Information

-- -----------------------------------------------------
-- Schema db_ledger
--
-- Ledger Money Information
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_ledger` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `db_ledger` ;

-- -----------------------------------------------------
-- Table `db_ledger`.`CAT_Expense_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`CAT_Expense_Type` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`CAT_Expense_Type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_expense_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ledger`.`CAT_Vendor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`CAT_Vendor` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`CAT_Vendor` (
  `idVendor` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  PRIMARY KEY (`idVendor`),
  UNIQUE INDEX `id_vendor_UNIQUE` (`idVendor` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ledger`.`CAT_Financing_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`CAT_Financing_Type` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`CAT_Financing_Type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_financing_type_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ledger`.`Financing_Entity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`Financing_Entity` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`Financing_Entity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `financing_type_id` INT NOT NULL,
  `name` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_financing_entity_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `name_financing_entity_UNIQUE` (`name` ASC) ,
  INDEX `fk_financing_entity_financing_type_idx` (`financing_type_id` ASC),
  CONSTRAINT `fk_financing_entity_financing_type`
    FOREIGN KEY (`financing_type_id`)
    REFERENCES `db_ledger`.`CAT_Financing_Type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ledger`.`Currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`Currency` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`Currency` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `symbol` VARCHAR(2) NOT NULL,
  `conversion` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_currency_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `name_currency_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ledger`.`Owner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`Owner` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`Owner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `currency_id` INT NOT NULL,
  `email` VARCHAR(120) CHARACTER SET 'utf8' NOT NULL,
  `username` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `fullname` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_owner_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `email_owner_UNIQUE` (`email` ASC) ,
  INDEX `fk_owner_currency_idx` (`currency_id` ASC) ,
  CONSTRAINT `fk_owner_currency`
    FOREIGN KEY (`currency_id`)
    REFERENCES `db_ledger`.`Currency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ledger`.`CAT_Wallet_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`CAT_Wallet_Type` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`CAT_Wallet_Type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_wallet_type_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ledger`.`Wallet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`Wallet` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`Wallet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner_id` INT NOT NULL,
  `wallet_type_id` INT NOT NULL,
  `currency_id` INT NOT NULL,
  `name` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_wallet_UNIQUE` (`id` ASC) ,
  INDEX `fk_wallet_wallet_type_idx` (`wallet_type_id` ASC),
  INDEX `fk_wallet_owner_idx` (`owner_id` ASC) ,
  INDEX `fk_wallet_currency_idx` (`currency_id` ASC) ,
  CONSTRAINT `fk_wallet_wallet_type`
    FOREIGN KEY (`wallet_type_id`)
    REFERENCES `db_ledger`.`CAT_Wallet_Type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wallet_owner`
    FOREIGN KEY (`owner_id`)
    REFERENCES `db_ledger`.`Owner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wallet_currency`
    FOREIGN KEY (`currency_id`)
    REFERENCES `db_ledger`.`Currency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ledger`.`Cash`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`Cash` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`Cash` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `wallet_id` INT NOT NULL,
  `name` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `total` DOUBLE NOT NULL,
  `active` TINYINT(2) NOT NULL DEFAULT 1,
  INDEX `fk_cash_wallet_idx` (`wallet_id` ASC) ,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_cash_UNIQUE` (`id` ASC) ,
  CONSTRAINT `fk_cash_wallet`
    FOREIGN KEY (`wallet_id`)
    REFERENCES `db_ledger`.`Wallet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ledger`.`Saving`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`Saving` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`Saving` (
  `id` INT NOT NULL,
  `wallet_id` INT NOT NULL,
  `entity_id` INT NOT NULL,
  `name` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `interes_rate` DOUBLE NOT NULL DEFAULT 0,
  `total` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_saving_UNIQUE` (`id` ASC) ,
  INDEX `fk_savings_financing_wallet_idx` (`entity_id` ASC),
  INDEX `fk_savings_financing_entity_idx` (`wallet_id` ASC) ,
  CONSTRAINT `fk_savings_financing_wallet`
    FOREIGN KEY (`wallet_id`)
    REFERENCES `db_ledger`.`Wallet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_savings_financing_entity`
    FOREIGN KEY (`entity_id`)
    REFERENCES `db_ledger`.`Financing_Entity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ledger`.`Debit_Card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`Debit_Card` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`Debit_Card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `saving_id` INT NOT NULL,
  `name` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `cut_day` INT(2) NOT NULL,
  `ending` VARCHAR(5) CHARACTER SET 'utf8' NOT NULL,
  `expiration` VARCHAR(7) CHARACTER SET 'utf8' NOT NULL,
  `card_type` TINYINT(4) NOT NULL,
  `color` VARCHAR(12) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_debit_card_UNIQUE` (`id` ASC) ,
  INDEX `fk_debit_card_savings_idx` (`saving_id` ASC) ,
  CONSTRAINT `fk_debit_card_savings`
    FOREIGN KEY (`saving_id`)
    REFERENCES `db_ledger`.`Saving` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ledger`.`Credit_Card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`Credit_Card` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`Credit_Card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `entity_id` INT NOT NULL,
  `wallet_id` INT NOT NULL,
  `name` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `credit` DOUBLE NOT NULL,
  `use_credit` DOUBLE NOT NULL,
  `cut_day` INT(2) NOT NULL,
  `due_day` INT(2) NOT NULL,
  `expiration` VARCHAR(7) CHARACTER SET 'utf8' NOT NULL,
  `card_type` TINYINT(4) NOT NULL,
  `ending` VARCHAR(5) CHARACTER SET 'utf8' NULL DEFAULT '00000',
  `color` VARCHAR(12) CHARACTER SET 'utf8' NULL DEFAULT 'black',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_credit_card_UNIQUE` (`id` ASC) ,
  INDEX `fk_credit_card_financing_entity_idx` (`entity_id` ASC) ,
  INDEX `fk_credit_card_wallet_idx` (`wallet_id` ASC) ,
  CONSTRAINT `fk_credit_card_financing_entity`
    FOREIGN KEY (`entity_id`)
    REFERENCES `db_ledger`.`Financing_Entity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_credit_card_wallet`
    FOREIGN KEY (`wallet_id`)
    REFERENCES `db_ledger`.`Wallet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ledger`.`Digital_Wallet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`Digital_Wallet` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`Digital_Wallet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `wallet_id` INT NOT NULL,
  `entity_id` INT NOT NULL,
  `name` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_digital_wallet_UNIQUE` (`id` ASC) ,
  INDEX `fk_digital_wallet_wallet_idx` (`wallet_id` ASC),
  INDEX `fk_digital_wallet_financing_entity_idx` (`entity_id` ASC) ,
  CONSTRAINT `fk_digital_wallet_wallet`
    FOREIGN KEY (`wallet_id`)
    REFERENCES `db_ledger`.`Wallet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_digital_wallet_financing_entity`
    FOREIGN KEY (`entity_id`)
    REFERENCES `db_ledger`.`Financing_Entity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ledger`.`Payment_Frequency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`Payment_Frequency` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`Payment_Frequency` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `months` INT(2) NOT NULL,
  `years` INT(2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idFrecuenciaPago_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `nombre_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ledger`.`Subscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`Subscription` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`Subscription` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `currency_id` INT NOT NULL,
  `wallet_id` INT NOT NULL,
  `payment_frequency_id` INT NOT NULL,
  `name` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `price` DOUBLE NOT NULL DEFAULT 0,
  `active` TINYINT(2) NOT NULL DEFAULT 1,
  `charge_day` INT(2) NOT NULL,
  `last_payment_date` DATE NOT NULL,
  `exchange_rate` DOUBLE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_subscription_UNIQUE` (`id` ASC) ,
  INDEX `fk_subscription_currency_idx` (`currency_id` ASC) ,
  INDEX `fk_subscription_wallet_idx` (`wallet_id` ASC),
  INDEX `fk_subscription_payment_frequency_idx` (`payment_frequency_id` ASC) ,
  CONSTRAINT `fk_subscription_currency`
    FOREIGN KEY (`currency_id`)
    REFERENCES `db_ledger`.`Currency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subscription_wallet`
    FOREIGN KEY (`wallet_id`)
    REFERENCES `db_ledger`.`Wallet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subscription_payment_frequency`
    FOREIGN KEY (`payment_frequency_id`)
    REFERENCES `db_ledger`.`Payment_Frequency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ledger`.`Subscription_Payment_History`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`Subscription_Payment_History` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`Subscription_Payment_History` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subscription_id` INT NOT NULL,
  `payment_date` DATE NOT NULL,
  `total` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_Subscription_Payment_History_Subscriptions1_idx` (`subscription_id` ASC) ,
  CONSTRAINT `fk_Subscription_Payment_History_Subscriptions1`
    FOREIGN KEY (`subscription_id`)
    REFERENCES `db_ledger`.`Subscription` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ledger`.`Expense`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`Expense` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`Expense` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `wallet_id` INT NOT NULL,
  `expense_type_id` INT NOT NULL,
  `vendor_id` INT NOT NULL,
  `description` VARCHAR(120) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `total` DOUBLE NOT NULL,
  `buy_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_expense_UNIQUE` (`id` ASC) ,
  INDEX `fk_expense_vendor_idx` (`vendor_id` ASC) ,
  INDEX `fk_expense_wallet_idx` (`wallet_id` ASC),
  INDEX `fk_expense_expense_type_idx` (`expense_type_id` ASC) ,
  CONSTRAINT `fk_expense_vendor`
    FOREIGN KEY (`vendor_id`)
    REFERENCES `db_ledger`.`CAT_Vendor` (`idVendor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_expense_wallet`
    FOREIGN KEY (`wallet_id`)
    REFERENCES `db_ledger`.`Wallet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_expense_expense_type`
    FOREIGN KEY (`expense_type_id`)
    REFERENCES `db_ledger`.`CAT_Expense_Type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ledger`.`Monthly_With_No_Interest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`Monthly_With_No_Interest` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`Monthly_With_No_Interest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `credit_card_id` INT NOT NULL,
  `expense_id` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `months` INT(2) NOT NULL,
  `paid_months` INT(2) NOT NULL DEFAULT 0,
  `archived` INT(2) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_monthly_no_interest_credit_card` (`credit_card_id` ASC) ,
  INDEX `fk_monthly_no_interest_expense_idx` (`expense_id` ASC) ,
  UNIQUE INDEX `id_monthly_no_interest_UNIQUE` (`id` ASC) ,
  CONSTRAINT `fk_monthly_no_interest_credit_card`
    FOREIGN KEY (`credit_card_id`)
    REFERENCES `db_ledger`.`Credit_Card` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_monthly_no_interest_expense`
    FOREIGN KEY (`expense_id`)
    REFERENCES `db_ledger`.`Expense` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ledger`.`Investment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`Investment` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`Investment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner_id` INT NOT NULL,
  `currency_id` INT NOT NULL,
  `name` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `interest_rate` DOUBLE NOT NULL,
  `description` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL,
  `total` DOUBLE NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_investment_owner_idx` (`owner_id` ASC) ,
  INDEX `fk_investment_currency_idx` (`currency_id` ASC) ,
  UNIQUE INDEX `id_investment_UNIQUE` (`id` ASC) ,
  CONSTRAINT `fk_investment_owner`
    FOREIGN KEY (`owner_id`)
    REFERENCES `db_ledger`.`Owner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_investment_currency`
    FOREIGN KEY (`currency_id`)
    REFERENCES `db_ledger`.`Currency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ledger`.`Beneficiary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`Beneficiary` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`Beneficiary` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner_id` INT NOT NULL,
  `name` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_beneficiary_UNIQUE` (`id` ASC) ,
  INDEX `fk_beneficiary_owner_idx` (`owner_id` ASC) ,
  CONSTRAINT `fk_beneficiary_owner`
    FOREIGN KEY (`owner_id`)
    REFERENCES `db_ledger`.`Owner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ledger`.`Lend_Money`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`Lend_Money` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`Lend_Money` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner_id` INT NOT NULL,
  `expense_id` INT NOT NULL,
  `beneficiary_id` INT NOT NULL,
  `payment_frequency_id` INT NOT NULL,
  `total` DOUBLE NOT NULL,
  `interest_rate` DOUBLE NOT NULL DEFAULT 0,
  `paid` DOUBLE NOT NULL DEFAULT 0,
  `last_payment_date` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lend_money_expense_idx` (`expense_id` ASC) ,
  INDEX `fk_lend_money_owner_idx` (`owner_id` ASC) ,
  INDEX `fk_lend_money_beneficiary_idx` (`beneficiary_id` ASC) ,
  INDEX `fk_lend_money_payment_frequency` (`payment_frequency_id` ASC) ,
  UNIQUE INDEX `id_lend_money_UNIQUE` (`id` ASC) ,
  CONSTRAINT `fk_lend_money_expense`
    FOREIGN KEY (`expense_id`)
    REFERENCES `db_ledger`.`Expense` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lend_money_owner`
    FOREIGN KEY (`owner_id`)
    REFERENCES `db_ledger`.`Owner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lend_money_beneficiary`
    FOREIGN KEY (`beneficiary_id`)
    REFERENCES `db_ledger`.`Beneficiary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lend_money_payment_frequency`
    FOREIGN KEY (`payment_frequency_id`)
    REFERENCES `db_ledger`.`Payment_Frequency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ledger`.`Credit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`Credit` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`Credit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `payment_frequency_id` INT NOT NULL,
  `wallet_id` INT NOT NULL,
  `name` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `description` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL,
  `total` DOUBLE NOT NULL,
  `last_payment` DATE NOT NULL,
  `interest_rate` DOUBLE NULL DEFAULT 0,
  `paid` DOUBLE NOT NULL DEFAULT 0,
  `remaining_payment` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_credit_UNIQUE` (`id` ASC) ,
  INDEX `fk_credit_payment_frequency_idx` (`payment_frequency_id` ASC) ,
  INDEX `fk_credit_wallet_idx` (`wallet_id` ASC) ,
  CONSTRAINT `fk_credit_payment_frequency`
    FOREIGN KEY (`payment_frequency_id`)
    REFERENCES `db_ledger`.`Payment_Frequency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_credit_wallet`
    FOREIGN KEY (`wallet_id`)
    REFERENCES `db_ledger`.`Wallet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ledger`.`Digital_Wallet_Payment_Wallet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ledger`.`Digital_Wallet_Payment_Wallet` ;

CREATE TABLE IF NOT EXISTS `db_ledger`.`Digital_Wallet_Payment_Wallet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `digital_wallet_id` INT NOT NULL,
  `wallet_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_digital_wallet_payment_wallet_idx` (`digital_wallet_id` ASC) ,
  INDEX `fk_wallet_payment_wallet_idx` (`wallet_id` ASC),
  UNIQUE INDEX `id_digital_payment_wallet_UNIQUE` (`id` ASC) ,
  CONSTRAINT `fk_digital_wallet_payment_wallet`
    FOREIGN KEY (`digital_wallet_id`)
    REFERENCES `db_ledger`.`Digital_Wallet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wallet_payment_wallet`
    FOREIGN KEY (`wallet_id`)
    REFERENCES `db_ledger`.`Wallet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
